### ISSUE TITLE
My organization will block this 

### ISSUE THREAD

**Issue by chuymtz** [quarto-ext/code-filename#4]
I really want to try this extension but my organization blocks this url. If I download the tar file how can I manually install it?

**Comment by cderv** [comment]
You should be able to install from the archive file directly. See more in this page: https://quarto.org/docs/extensions/distributing.html#archive-files

> my organization blocks this url

Your organization is blocking github.com ? Or is there anything specific in our repo that trigger a flag for your organization ?

**Comment by chuymtz** [comment]
Thank you for your reply! I think you pointed me to the right section in the docs. I can access github and dowload the zip file. What I could not do is run something like 

```
quarto install extension quarto-ext/lightbox
```
But as you pointed out 
```
quarto install extension ~/Downloads/shorty.zip
```
should do the trick. I will give this a try.

**Comment by chuymtz** [comment]
I downloaded the zip file `code-filename-main.zip` and ran `quarto install extension .\code-filename-main.zip`
```
(env) PS C:\Users\...\adam-website> quarto install extension .\code-filename-main.zip
(/) Unzippinginvalid command 'hook'
Invoke-Expression : Cannot bind argument to parameter 'Command' because it is an empty string.
At C:\Users\...\Documents\WindowsPowerShell\profile.ps1:4 char:119
+ ... onda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
+                                                         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:PSObject) [Invoke-Expression], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.InvokeExpressionCommand

[>] Unzipping
    Found 0 extensions.
ERROR: Invalid extension
The extension staged at C:\Users\...\AppData\Local\Temp\quarto-sessionc7d3ef62\9934e50e\1d29da75\staged does not provide any valid extensions.
```

**Comment by chuymtz** [comment]
I think I was able to fix my mistake. I unzipped the file and ran the install command two directories down the rabbit hole. 
```
(env) PS C:\Users\...\Projects\adam-website> quarto install extension .\code-filename-main\code-filename-main\
    Found 1 extension.

The following changes will be made:
Code Filename   [Install]   0.1.0 (filter)
 ? Would you like to continue (Y/n) » Yes

[>] Extension installation complete.
```

**Comment by cderv** [comment]
Interesting 🤔 

@dragonstyle does installing zip file downloaded from github repo is supposed to work ? 

It seems like we could try to handle this case where the zip contains one more folder parent folder before the extension folder.

**Comment by dragonstyle** [comment]
We don't currently -  we expect the `_extensions` folder to be at the root level of an extension archive. We could consider probing if there is one and only one folder when we open the archive (e.g. drill one level deeper) - would definitely be nice to support a simple DL of GitHub source tarball and install...

**Comment by cderv** [comment]
I opened an issue about this idea.

**Comment by chuymtz** [comment]
Thank you @cderv. Great community.
